### ISSUE TITLE
Database Schema 

### ISSUE THREAD

**Issue by Aditya-Dawadikar** [devscollab/skill-board-api#4]
Create database schema in the skill-board-api/app/models/ folder, for Studentuser and Superuser
Note: I'll share the connection string and database access shortly
**Required fields for SuperUser**
----------------------Login
Email: str
password: str
phone: Number/str
Name: str
linkedIn: str
github: str
--------------------------Optionals
introduction - str
gender - str
age - number
mother tongue - str
languages known - str
-------------------------Meta Data
timestamp - str 
hasAdminAccess - boolean
github metadata object - object

**Required fields for StudentUser** 
----------------------Personal
Name - str
College - str
Department - str
Year - str
Division - str
Roll Number - str
----------------------Social
phone number - number validated for mobile no
is whatsapp available - boolean
email - str validated for emal
github profile url - str validated for url
linkedin profile url - str validated for url
personal website - str validated for url
resume - str validated for url
---------------------------Skills
skills - array of str
projects for every skill - array of str validated for url
top-skill - number (index of the top skill from skills array)
cgpa till date - number float
--------------------------Optionals
introduction - str
gender - str
age - number
mother tongue - str
languages known - str
-------------------------Meta Data
timestamp - str 
hasAdminAccess - boolean
github metadata object - object

**Comment by bhavansh** [comment]
have created a pull req check it
