### ISSUE TITLE
Expiration of OTP

### ISSUE THREAD

**Issue by Aditya-Dawadikar** [devscollab/skill-board-api#40]
1. Set timestamp as true in otps schema.
2. Add TTL indexing on the **otps collection** in mongodb.
3. Set the expiration time to **10 mins(600secs)**.
4. Remove the background process of cleaning the OTP from the server.js file.
![image](https://user-images.githubusercontent.com/54301325/94840145-98e73880-0435-11eb-9dbe-059bf1413ec6.png)

ref: **https://docs.mongodb.com/manual/core/index-ttl/**

**Comment by khushi2912** [comment]
Can you assign this to me please?

**Comment by Aditya-Dawadikar** [comment]
@khushi2912 if you are confident enough then, go ahead. You may require the connection string and other credentials for performing the task. email us at adityadawadikar2000@gmail.com for the same.

**Comment by khushi2912** [comment]
> @khushi2912 if you are confident enough then, go ahead. You may require the connection string and other credentials for performing the task. email us at [adityadawadikar2000@gmail.com](mailto:adityadawadikar2000@gmail.com) for the same.

Yes sure!

**Comment by Aditya-Dawadikar** [comment]
Go through the contribution guidelines and start hacking
