### ISSUE TITLE
Document migration

### ISSUE THREAD

**Issue by Aditya-Dawadikar** [devscollab/skill-board-api#41]
Make use of the **db.collection.copyTo()** method to copy the unverified student document to the student collection and delete the document from the profiles collection. 

note: remove existing code.

path: **app/controllers/profileVerification.js**

ref: https://docs.mongodb.com/manual/reference/method/db.collection.copyTo/

**Comment by hey-mikey** [comment]
Can I work on this?

**Comment by tejasmorkar** [comment]
Sure, you can start working on it. 
While creating the PR, do not forget to link it to this issue 😄

**Comment by hey-mikey** [comment]
I'm looking at this now -- I'm in over my head, I think. :) Just removed the assignment so someone else can grab it. Sorry about that.
