### ISSUE TITLE
Create a Search bar api Logic

### ISSUE THREAD

**Issue by bhavansh** [devscollab/skill-board-api#42]
1) Create a Search bar Api file in app -> controllers as search.js
2) make use of regex or fuzzy logic to fetch data from the database. basically a custom query
3) Search logic to search based on name
4) Search logic to search based on skills

**[Reference - 1](https://docs.mongodb.com/manual/text-search/)**
**[Reference - 2](https://docs.mongodb.com/manual/reference/operator/aggregation/regexMatch/)**
**[Reference - 3](https://www.npmjs.com/package/mongoose-fuzzy-searching)**

**Comment by megabyte98** [comment]
can you assign this issue to me ?

**Comment by megabyte98** [comment]
how do i test the app locally the .env file is in .gitignore . so mongo is not connecting

**Comment by Aditya-Dawadikar** [comment]
> how do i test the app locally the .env file is in .gitignore . so mongo is not connecting

I'm not sure if I can give you access to the main database. Can you create a test database on your own MongoDB atlas account?
If not then let us know.

**Comment by megabyte98** [comment]
ok I will create a test database then

**Comment by megabyte98** [comment]
But i would have to set up the entire database then with all details of students

**Comment by bhavansh** [comment]
@megabyte98  Send your Email at guptabhavansh@gmail.com and I will send you the connection string

**Comment by megabyte98** [comment]
hey i have implemented the name search but with skills do yo want to search with skill or based on primary and secondary?

**Comment by megabyte98** [comment]
can you please review and update is any changes required :)

**Comment by Aditya-Dawadikar** [comment]
I'm closing this issue. If we need some more functionality added to it, then we might reopen the issue.
