### ISSUE TITLE
Filter API to Filter Students Based on rating

### ISSUE THREAD

**Issue by bhavansh** [devscollab/skill-board-api#43]
Filter API to Filter Students Based on rating

**Needs Further Discussion**

**Comment by megabyte98** [comment]
can you please assign this issue to me and elaborate on what you need to implement

**Comment by Aditya-Dawadikar** [comment]
> Hello @bhavansh
> I would like to work on this issue.
> 
> My proposed solution is to create an endpoint and use the `rating` property of the `studentSchema` to sort the list of students.
> 
> Can I be assigned to this?

You are right! The main problem is we have not yet figured out the rating algorithm. But we can still deliver this functionality if we can put some dummy data into the database. And that way it can still work. You may start working on this issue.

https://devscollab.com/skill-board/listing.html

check out this link. It's the UI on which our Frontend team is still working on.
we will not only be filtering data based on the rating field from the schema , but also the primaryskill, secondaryskill.
Let me know if you can complete it or if you need further details.

**Comment by ruddha2001** [comment]
@tejasmorkar this will not be an issue. Pretty easy stuff.
How about I create an endpoint with multiple query support?
Like,
/search - to search by rating (default)
/search?prop=primary - to search by primarySkill
/search?prop=secondary - to search by secondarySkill

Will this work for you and your team?

**Comment by Aditya-Dawadikar** [comment]
> @Aditya-Dawadikar this will not be an issue. Pretty easy stuff.
> How about I create an endpoint with multiple query support?
> Like,
> `/search` - to search by rating (default)
> `/search?prop=primary` - to search by primarySkill
> `/search?prop=secondary` - to search by secondarySkill
> 
> Will this work for you and your team?
> 
> I can also combine multiple parameters. Like,
> `/search?prop1=rating&prop2=primary&prop3=secondary` for sorting by rating, primary and secondary. The client chooses the order on what to use. Any combination of 3 props or even less than 3 props fine.
> 
> Let me know which one is feasible for your project.

This works for us, you may start working on it.

**Comment by bhavansh** [comment]
@ruddha2001  Send your Email at guptabhavansh@gmail.com and I will send you the connection string
