### ISSUE TITLE
Sort Api

### ISSUE THREAD

**Issue by Aditya-Dawadikar** [devscollab/skill-board-api#44]
Sort Api for ascending or descending students listing based on student rating

note: needs further discussion

**Comment by harikesh409** [comment]
Can you elaborate on how you want it?

**Comment by megabyte98** [comment]
Basically you need a route to sort the students based on rating and return it  which is in your student schema

**Comment by megabyte98** [comment]
can you please assign this issue to me ?

**Comment by harikesh409** [comment]
> Basically you need a route to sort the students based on rating and return it which is in your student schema

That is a way but a much-optimized one would be doing something like having sort attributes so that we can do dymanic sorting.

**Comment by jennypoon** [comment]
> > Basically you need a route to sort the students based on rating and return it which is in your student schema
> 
> That is a way but a much-optimized one would be doing something like having sort attributes so that we can do dymanic sorting.

You can also pass that attribute into the query: https://docs.mongodb.com/manual/reference/method/cursor.sort/#cursor.sort

**Comment by Aditya-Dawadikar** [comment]
> > > Basically you need a route to sort the students based on rating and return it which is in your student schema
> > 
> > 
> > That is a way but a much-optimized one would be doing something like having sort attributes so that we can do dymanic sorting.
> 
> You can also pass that attribute into the query: https://docs.mongodb.com/manual/reference/method/cursor.sort/#cursor.sort

We were planning to do the same. 
1. create an endpoint that can send the sorted data
2. require the attribute from the query
3. apply the query on the database
4. return the response

The attributes that we will be using to sort the student user are yet to be discussed with our team. We will update the issue asap, then you may start working on it. For now, you may sort the student users based on the rating attribute from the schema and the "rating" attribute must be sent to the server as part of the query string.

**Comment by raghavddps2** [comment]
@Aditya-Dawadikar 
Can I take this up?
