### ISSUE TITLE
Rating API

### ISSUE THREAD

**Issue by Aditya-Dawadikar** [devscollab/skill-board-api#45]
This API be a POST method that will rate individual student using a background process

note: needs further discussion

**Comment by jennypoon** [comment]
Hello! Could you elaborate on what the requirements are for rating an individual student?

**Comment by tejasmorkar** [comment]
Right now, the plan is that we will receive a GitHub username from the frontend and we have to fetch all the relevant metadata such as the number of public commits, PRs, issues, stars etc. and calculate a rating out of 5.

We are currently brainstorming on an algorithm/ function that can fairly rate the students out of 5 based on these parameters. 

Feel free to put forward any ideas that you have.

**Comment by megabyte98** [comment]
so first fetch data using github api then normailze it based on some factor like out of 10 using a function  and then using that rating implement sort and filter

**Comment by Aditya-Dawadikar** [comment]
> Right now, the plan is that we will receive a GitHub username from the frontend and we have to fetch all the relevant metadata such as the number of public commits, PRs, issues, stars etc. and calculate a rating out of 5.
> 
> We are currently brainstorming on an algorithm/ function that can fairly rate the students out of 5 based on these parameters.
> 
> Feel free to put forward any ideas that you have.

Right now this issue can be divided into 2 subtasks. 
1. create the rating algorithm
2. rate the user

Creating the rating algorithm needs some serious brainstorming on our part, and we won't assign you that task.
For now, you can create a function that can receive a parameter named "rating" and assign this value to the student
user. This function must be exported from the module so that it can be used anywhere it is necessary.

model path: app/models/student.js
controller path: app/controllers/student.js
