### ISSUE TITLE
Accept a key "pronoun" from the request body for registration API

### ISSUE THREAD

**Issue by Aditya-Dawadikar** [devscollab/skill-board-api#47]
Add a new key called "pronoun" in the "optionals" object inside the registration request handlers.

| path of file                           | function name     | line number for insertion | code to insert                        |
|----------------------------------------|-------------------|---------------------------|---------------------------------------|
| app/controllers/register.js            | registerStudent   | 63                        | pronoun : req.body.optionals.pronoun, |
| app/controllers/register.js            | registerSuperuser | 139                       | pronoun : req.body.optionals.pronoun, |
| app/controllers/profileVerification.js | approve           | 78                        | pronoun : doc[0].optionals.pronoun    |

**Comment by bhavansh** [comment]
Issue solved during previous commit
