### ISSUE TITLE
Registration for Student , superuser

### ISSUE THREAD

**Issue by Aditya-Dawadikar** [devscollab/skill-board-api#8]
This logic goes into the app/controllers/register.js file.
test definition is already written in there, replace it with user registration logic.
---
logic :
1. take the required data from req.body
2. validate the data
3. if data is invalid, send a bad request response with status code 401.
else save the data in database and send success response with status code 2000

![image](https://user-images.githubusercontent.com/54301325/91168256-f380cc80-e6f2-11ea-99ac-31a0742b06d5.png)

**Comment by bhavansh** [comment]
I will try to complete it by tomorrow
